### PR TITLE
TRD related macros

### PR DESCRIPTION
**Pull request by sourav-tarafdar**
Added  common/G4_TRD.C  , implemented detector macro in detectors/EICDetector/Fun4All_G4_EICDetector.C and G4Setup_EICDetector.C

### CODE REVIEW

**Comment by cdean-github** [comment]
Hi @sourav-tarafdar, 

I'm getting an overlap warning from the TRD:
```
Checking overlaps for volume H_CAP_TRD_Physics (G4Tubs) ...
-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : GeomVol1002
      issued by : G4PVPlacement::CheckOverlaps()
Overlap with volume already placed !
          Overlap is detected for volume H_CAP_TRD_Physics:0 (G4Tubs)
          with HadronForwardChamber_0:0 (G4ExtrudedSolid) volume's
          local point (-45.6085,-20.4905,2059.58), overlapping by at least: 4.45649 cm
NOTE: Reached maximum fixed number -1- of overlaps reports for this volume !
*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------
```
and another from the BMMG
```
-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : GeomVol1002
      issued by : G4PVPlacement::CheckOverlaps()
Overlap with volume already placed !
          Overlap is detected for volume BMT_0_0:0 (G4Tubs)
          with ETrackingConeService_3_28:0 (G4Cons) volume's
          local point (-427.653,416.869,-27.8857), overlapping by at least: 343.653 um
NOTE: Reached maximum fixed number -1- of overlaps reports for this volume !
*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------
```

**Comment by sourav-tarafdar** [comment]
> Hi @sourav-tarafdar,
> 
> I'm getting an overlap warning from the TRD:
> 
> ```
> Checking overlaps for volume H_CAP_TRD_Physics (G4Tubs) ...
> -------- WWWW ------- G4Exception-START -------- WWWW -------
> *** G4Exception : GeomVol1002
>       issued by : G4PVPlacement::CheckOverlaps()
> Overlap with volume already placed !
>           Overlap is detected for volume H_CAP_TRD_Physics:0 (G4Tubs)
>           with HadronForwardChamber_0:0 (G4ExtrudedSolid) volume's
>           local point (-45.6085,-20.4905,2059.58), overlapping by at least: 4.45649 cm
> NOTE: Reached maximum fixed number -1- of overlaps reports for this volume !
> *** This is just a warning message. ***
> -------- WWWW -------- G4Exception-END --------- WWWW -------
> ```
> 
Hi @cdean-github , may I know which subsystem needs to be turned on for HadronForwardChamber_0 ? I will think it should be "FHCAL" but seems there is nothing like that in the Fun4All macro. The closest one if "LFHCAL" but it is sitting far off from H_CAP_TRD. Am I missing something ?

**Comment by blackcathj** [comment]
That is the forward beam chamber. The suggestion for all detectors is: never touch it. Note it is asymmetric towards the -x side


> > Hi @sourav-tarafdar,
> > I'm getting an overlap warning from the TRD:
> > ```
> > Checking overlaps for volume H_CAP_TRD_Physics (G4Tubs) ...
> > -------- WWWW ------- G4Exception-START -------- WWWW -------
> > *** G4Exception : GeomVol1002
> >       issued by : G4PVPlacement::CheckOverlaps()
> > Overlap with volume already placed !
> >           Overlap is detected for volume H_CAP_TRD_Physics:0 (G4Tubs)
> >           with HadronForwardChamber_0:0 (G4ExtrudedSolid) volume's
> >           local point (-45.6085,-20.4905,2059.58), overlapping by at least: 4.45649 cm
> > NOTE: Reached maximum fixed number -1- of overlaps reports for this volume !
> > *** This is just a warning message. ***
> > -------- WWWW -------- G4Exception-END --------- WWWW -------
> > ```
> 
> Hi @cdean-github , may I know which subsystem needs to be turned on for HadronForwardChamber_0 ? I will think it should be "FHCAL" but seems there is nothing like that in the Fun4All macro. The closest one if "LFHCAL" but it is sitting far off from H_CAP_TRD. Am I missing something ?

**Comment by cdean-github** [comment]
Hi @sourav-tarafdar, can the TRD be placed in the macro or does this require an update in the compiled software? I would suggest checking out your macros and placing the TRD and new barrel detector to remove the overlaps. When this is OK, I can merge the PR

> That is the forward beam chamber. The suggestion for all detectors is: never touch it. Note it is asymmetric towards the -x side
> 
> > > Hi @sourav-tarafdar,
> > > I'm getting an overlap warning from the TRD:
> > > ```
> > > Checking overlaps for volume H_CAP_TRD_Physics (G4Tubs) ...
> > > -------- WWWW ------- G4Exception-START -------- WWWW -------
> > > *** G4Exception : GeomVol1002
> > >       issued by : G4PVPlacement::CheckOverlaps()
> > > Overlap with volume already placed !
> > >           Overlap is detected for volume H_CAP_TRD_Physics:0 (G4Tubs)
> > >           with HadronForwardChamber_0:0 (G4ExtrudedSolid) volume's
> > >           local point (-45.6085,-20.4905,2059.58), overlapping by at least: 4.45649 cm
> > > NOTE: Reached maximum fixed number -1- of overlaps reports for this volume !
> > > *** This is just a warning message. ***
> > > -------- WWWW -------- G4Exception-END --------- WWWW -------
> > > ```
> > 
> > 
> > Hi @cdean-github , may I know which subsystem needs to be turned on for HadronForwardChamber_0 ? I will think it should be "FHCAL" but seems there is nothing like that in the Fun4All macro. The closest one if "LFHCAL" but it is sitting far off from H_CAP_TRD. Am I missing something ?

**Comment by sourav-tarafdar** [comment]
Hi @blackcathj and @cdean-github , so far the only thing one can control from macro for TRD is it's z location, inner Radius, outer radius and length. The origin for x and y are at (0,0).  It appears from Jin's suggestion that I need to offset the x coordinate for the center of TRD. Probably better if I pass on a parameter for "x-center " position from macro to compiled code .
> Hi @sourav-tarafdar, can the TRD be placed in the macro or does this require an update in the compiled software? I would suggest checking out your macros and placing the TRD and new barrel detector to remove the overlaps. When this is OK, I can merge the PR
> 
> > That is the forward beam chamber. The suggestion for all detectors is: never touch it. Note it is asymmetric towards the -x side
> > > > Hi @sourav-tarafdar,
> > > > I'm getting an overlap warning from the TRD:
> > > > ```
> > > > Checking overlaps for volume H_CAP_TRD_Physics (G4Tubs) ...
> > > > -------- WWWW ------- G4Exception-START -------- WWWW -------
> > > > *** G4Exception : GeomVol1002
> > > >       issued by : G4PVPlacement::CheckOverlaps()
> > > > Overlap with volume already placed !
> > > >           Overlap is detected for volume H_CAP_TRD_Physics:0 (G4Tubs)
> > > >           with HadronForwardChamber_0:0 (G4ExtrudedSolid) volume's
> > > >           local point (-45.6085,-20.4905,2059.58), overlapping by at least: 4.45649 cm
> > > > NOTE: Reached maximum fixed number -1- of overlaps reports for this volume !
> > > > *** This is just a warning message. ***
> > > > -------- WWWW -------- G4Exception-END --------- WWWW -------
> > > > ```
> > > 
> > > 
> > > Hi @cdean-github , may I know which subsystem needs to be turned on for HadronForwardChamber_0 ? I will think it should be "FHCAL" but seems there is nothing like that in the Fun4All macro. The closest one if "LFHCAL" but it is sitting far off from H_CAP_TRD. Am I missing something ?

**Comment by blackcathj** [comment]
Sure. @sourav-tarafdar  Please note when using offset x-center, it changes the outer radius too. 

For simple test, suggest use a larger beam chamber opening. 
For more detailed model, suggest write a dedicated detector code, which can use different x-offset for inner and outer boundaries. Example is the TTL code. 

> Hi @blackcathj and @cdean-github , so far the only thing one can control from macro for TRD is it's z location, inner Radius, outer radius and length. The origin for x and y are at (0,0). It appears from Jin's suggestion that I need to offset the x coordinate for the center of TRD. Probably better if I pass on a parameter for "x-center " position from macro to compiled code .
>

**Comment by sourav-tarafdar** [comment]
Hi @blackcathj and @cdean-github , so apparently I have been always using IP 8 configuration and it never needed beam chamber. I switched to IP 6 and increased the inner R of TRD and the overlap issue is gone. For the time being I will keep the inner R of TRD = 10 cm . 
About barrel micromega aka BMMG, the overlap between inner layer of BMMG and "tracking servises" needs more study . I have been doing the QA evaluation with micromega without using tracking services.
Another pressing matter is making pull request for Barrel mRPC ToF . If I make a new pull request from my fork then automatically it pushes to the opened pull request aka PR 42. Any way I can avoid it ? 

> Sure. @sourav-tarafdar Please note when using offset x-center, it changes the outer radius too.
> 
> For simple test, suggest use a larger beam chamber opening. For more detailed model, suggest write a dedicated detector code, which can use different x-offset for inner and outer boundaries. Example is the TTL code.
> 
> > Hi @blackcathj and @cdean-github , so far the only thing one can control from macro for TRD is it's z location, inner Radius, outer radius and length. The origin for x and y are at (0,0). It appears from Jin's suggestion that I need to offset the x coordinate for the center of TRD. Probably better if I pass on a parameter for "x-center " position from macro to compiled code .

**Comment by blackcathj** [comment]
> Another pressing matter is making pull request for Barrel mRPC ToF . If I make a new pull request from my fork then automatically it pushes to the opened pull request aka PR 42. Any way I can avoid it ?

Please use a new branch on your fork, then it will be a new PR

**Comment by sourav-tarafdar** [comment]
Hi @blackcathj  and @cdean-github , latest commit for this pull request doesn't have any more overlap between Barrel MMG inner layer with Tracking service cone and between TRD volume with beam pipe chamber. Changes made in the last commit are
1. Radial positions of BMMG changed to 45, 47.4 and 67.4 cm (almost same as default mRwell radial locations) in macro G4_BMMGT.C
2. Inner radius of TRD changed from 5 cm to 15 cm .
3. Added also TRD gas active volume as an active flag in Fun4All macro.

**Pull request merged**
