### PR TITLE
Update on FST dimension and more

### PR DESCRIPTION
**Pull request by pingwong**
- update on FST dimension
- add a cylindrical supporting tube for the central, backward and forward tracking systems (see figure)
-checked overlaping
Screen Shot 2021-06-10 at 10 16 06 PM

### CODE REVIEW

**Comment by blackcathj** [comment]
Hi Ping

Thanks for the contribution. Please note the current master branch will be replaced with to-be newly integrated ECCE detector. Therefore, instead of merging into the current `ePHENIX`-like setup, your contribution will directly go to the new ECCE setup.

**Comment by pingwong** [comment]
@blackcathj Sounds good to me. 

I am confused by the organization of the branches. I thought I forked from the ECCE setup (see screenshot). Is there a newer branch of ECCE?

Screen Shot 2021-06-11 at 8 32 02 AM

**Comment by blackcathj** [comment]
You did it correctly. The new branch is still in preparation.

**Comment by blackcathj** [comment]
Thanks @pingwong , it is already integrated to the new detector branch via b165f3a

**Pull request closed without merging**
