### PR TITLE
New B0 Geometry

### PR DESCRIPTION
**Pull request by abylinkin**

### CODE REVIEW

**Comment by cdean-github** [comment]
HI @abylinkin 

I tried to run the macros but I got an error about a missing macro, I think it's ```G4_B0Tracking_EIC.C```

Also, there are some merge conflicts. 
```
detectors/EICDetector/Fun4All_G4_EICDetector.C
detectors/EICDetector/G4Setup_EICDetector.C 
```
look to be minor but I would likely break:
```
common/G4_hFarFwdBeamLine_EIC.C
```
if I tried to solve them myself. Could you look into them?

The f4a detector compiled code and I'm ready with the PR there once we confirm everything is OK with the macros.

Cheers,
Cameron

**Comment by abylinkin** [comment]
Hi Cameron,

Sorry, it looks like that I changed some older version of the repository -
that's why there are merge conflicts.

I got a message about it after I created a pull request, but I had to leave
for a meeting soon thereafter so didn't have time to resolve this.

I will let you know as soon as I am done with it.

Thank you!

Cheers, Sasha

чт, 16 дек. 2021 г. в 10:23, cdean-github ***@***.***>:

**Comment by cdean-github** [comment]
> 

Hi Sasha,

No worries, take all the time you need with this. Github will message me when any changes are made and I'll come back to this then.

Cheers,
Cameron

**Comment by abylinkin** [comment]
Hi Cameron,

For me it turned out to be easier to create a new pull request #96 to avoid
conflicts.
I hope that is not a problem. I can close #95 now.

Probably, you noticed this already - I created also a pull request to the
'fun4all_eicdetectors'
https://github.com/eic/fun4all_eicdetectors/pull/95
Basically, these two should go along.

And could you please put the new B0 calorimeter mapping?
getenv("CALIBRATIONROOT") << "/B0Ecal/mapping/B0ECAL_mapping_v2.txt"
as I do not have write access to the folder.

I placed my file here:
https://github.com/abylinkin/EIC_B0/blob/main/macros/B0ECAL_mapping_v2.txt

Thank you!

Let me know if there are any more issues.

Cheers, Sasha

чт, 16 дек. 2021 г. в 11:30, cdean-github ***@***.***>:

**Pull request closed without merging**
